version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: documents_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
